# Generated by Django 4.2.5 on 2023-10-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('tixt', models.TextField(verbose_name='Matni')),
                ('author', models.CharField(max_length=50, verbose_name='Avtor')),
                ('date', models.DateField(verbose_name='Vaqti')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
            },
        ),
    ]
